### PR TITLE
DERPFEST TALENT

### PR DESCRIPTION
**Pull request by ossfapper360**

### CODE REVIEW

**Comment by NurKeinNeid** [comment]
This is just bullshit. There's nothing wrong with it. Imagine your god Neobuddy stealing authorship of our commits and other projects. But this is ok for you obviously.

**Comment by ossfapper360** [comment]
> This is just bullshit. There's nothing wrong with it. Imagine your god Neobuddy stealing authorship of our commits and other projects. But this is ok for you obviously.

Who said he is my god 
i dont even know neobuddy before leaks

**Comment by NurKeinNeid** [comment]
Better learn to understand how development works before requesting non sense.

**Comment by ossfapper360** [comment]
> Better learn to understand how development works before requesting non sense.

yes from a cherry-pick expert i will become pro

**Comment by NurKeinNeid** [comment]
At least I know how to proper cherry-pick. Seems hard for most people in the scene.

**Comment by ossfapper360** [comment]
htt

> At least I know how to proper cherry-pick. Seems hard for most people in the scene.

whos scene their r 100's of roms in the market that r made by cherry-pick experts

**Comment by NurKeinNeid** [comment]
Exactly, there's nothing unique and no contribution at all

**Comment by ghost** [comment]
"at least i know how to cherry pick"

https://user-images.githubusercontent.com/93444783/172050732-4b204334-8ed3-473c-a1f0-419d1785671e.mp4

**Comment by clhexftw** [comment]
> This is just bullshit. There's nothing wrong with it. Imagine your god Neobuddy stealing authorship of our commits and other projects. But this is ok for you obviously.

ig acc to this leaking roms is fine as picking stuffs from oss roms and making that close is

**Comment by ghost** [comment]
imagine flexing how you can do `git cherry-pick`

what a sad life, at least learn how to do original bullshit

**Comment by ghost** [comment]
> > This is just bullshit. There's nothing wrong with it. Imagine your god Neobuddy stealing authorship of our commits and other projects. But this is ok for you obviously.
> 
> ig acc to this leaking roms is fine as picking stuffs from oss roms and making that close is

dw bro it's an L ROM like the other 400 copy-pasted ones

**Comment by clhexftw** [comment]
imagine kanging aex and not having guts to made it open

hope derpfest cherry-picker should have learned https://github.com/amogos-rom from this rom

**Comment by clhexftw** [comment]
> > > This is just bullshit. There's nothing wrong with it. Imagine your god Neobuddy stealing authorship of our commits and other projects. But this is ok for you obviously.
> > 
> > 
> > ig acc to this leaking roms is fine as picking stuffs from oss roms and making that close is
> 
> dw bro it's an L ROM like the other 400 copy-pasted ones

shouldn't we respect joey for doing these stuffs and still making it open? (just forgot he is a certified retard for a minute)

**Comment by ossfapper360** [comment]
> imagine flexing how you can do `git cherry-pick`
> 
> what a sad life, at least learn how to do original bullshit



> Exactly, there's nothing unique and no contribution at all

yes sad scene abt derpfest betterly known as kangfest

**Comment by ghost** [comment]
nah bro joey is too busy in doing livestreams on how to cherry pick from derpfest leaked source

**Comment by ghost** [comment]
> > imagine flexing how you can do `git cherry-pick`
> > what a sad life, at least learn how to do original bullshit
> 
> > Exactly, there's nothing unique and no contribution at all
> 
> yes sad scene abt derpfest betterly known as kangfest

bro at least they know they kang 🤓 

(you get it? kanging = funi hehe)

**Comment by clhexftw** [comment]
> nah bro joey is too busy in doing livestreams on how to cherry pick from derpfest leaked source

lmfao joey talent

**Comment by ossfapper360** [comment]
> > > imagine flexing how you can do `git cherry-pick`
> > > what a sad life, at least learn how to do original bullshit
> > 
> > 
> > > Exactly, there's nothing unique and no contribution at all
> > 
> > 
> > yes sad scene abt derpfest betterly known as kangfest
> 
> bro at least they know they kang nerd_face
> 
> (you get it? kanging = funi hehe)

:p

**Comment by Dark-Matter7232** [comment]
> At least I know how to proper cherry-pick. Seems hard for most people in the scene.

Lmao

**Comment by fryevia** [comment]
fuck sake, this troll, go fuck neobuddy butt. you fucker should read what Apache license is about @ossfapper360

**Comment by octaphene** [comment]
Imagine locking someone wen u cant face the truth rart fr

**Comment by octaphene** [comment]
> fuck sake, this troll, go fuck neobuddy butt. you fucker should read what Apache license is about @ossfapper360

acc to apache2 everything is fine a guy can make it oss too and?

**Comment by octaphene** [comment]
why apache2 only comes when someone asks u abt closed src rarts fr

**Comment by octaphene** [comment]
ppl rant devolutionx about kanging but u r on next level even beats our cherry-pick bot joey at least he have guts to not hide it

**Comment by fryevia** [comment]
> > fuck sake, this troll, go fuck neobuddy butt. you fucker should read what Apache license is about @ossfapper360
> 
> acc to apache2 everything is fine a guy can make it oss too and?

and? what? you can go private or open, and who said devolutionx kanging ? are you making money from this shit? why bother so much? talking about guts ? show your face rather using troll account, fucking kids, grow up.

**Comment by octaphene** [comment]
> 



> > > fuck sake, this troll, go fuck neobuddy butt. you fucker should read what Apache license is about @ossfapper360
> > 
> > 
> > acc to apache2 everything is fine a guy can make it oss too and?
> 
> and? what? you can go private or open, and who said devolutionx kanging ? are you making money from this shit? why bother so much? talking about guts ? show your face rather using troll account, fucking kids, grow up.

whenever someone leaks ur source u have issue but whenever someone asks or objects why u r closed apache2 license comes lol

**Comment by octaphene** [comment]
also i have no issues with evox but i have issues with joey himself how the fuck he is to insult indians

**Comment by octaphene** [comment]
every rom does cherry pick nowadays nothing new

**Comment by octaphene** [comment]
> > > fuck sake, this troll, go fuck neobuddy butt. you fucker should read what Apache license is about @ossfapper360
> > 
> > 
> > acc to apache2 everything is fine a guy can make it oss too and?
> 
> and? what? you can go private or open, and who said devolutionx kanging ? are you making money from this shit? why bother so much? talking about guts ? show your face rather using troll account, fucking kids, grow up.

also why u always bother when its about ur friends ur frnds r trolling cr than too u should be same ryt?

**Comment by azrim** [comment]
Look the actual thief, removed copyright. Then get caught up and amend the commit lmao. Suck neobuggy dick https://github.com/crdroidandroid/android_packages_apps_GameSpace/commit/5491d624c1c9f6ee5d33c165698eb9f7b9178979#diff-b8612be0ca7904aab0cafe581788e1b998893c4b681fdd0e1ea329168cc3938cR3

**Comment by octaphene** [comment]
> Look the actual thief, removed copyright. Then get caught up and amend the commit lmao. Suck neobuggy dick [crdroidandroid/android_packages_apps_GameSpace@5491d62#diff-b8612be0ca7904aab0cafe581788e1b998893c4b681fdd0e1ea329168cc3938cR3](https://github.com/crdroidandroid/android_packages_apps_GameSpace/commit/5491d624c1c9f6ee5d33c165698eb9f7b9178979#diff-b8612be0ca7904aab0cafe581788e1b998893c4b681fdd0e1ea329168cc3938cR3)

well thats wrong but he atleast accepted his mistake and fixed it later on not like derpfest devs derpfest is just rebranded aex with 34521 picks from few 10-20 roms and gamespace lol

**Comment by octaphene** [comment]
you dont need to become bad if someone else is bad - someone

**Comment by azrim** [comment]
> > Look the actual thief, removed copyright. Then get caught up and amend the commit lmao. Suck neobuggy dick [crdroidandroid/android_packages_apps_GameSpace@5491d62#diff-b8612be0ca7904aab0cafe581788e1b998893c4b681fdd0e1ea329168cc3938cR3](https://github.com/crdroidandroid/android_packages_apps_GameSpace/commit/5491d624c1c9f6ee5d33c165698eb9f7b9178979#diff-b8612be0ca7904aab0cafe581788e1b998893c4b681fdd0e1ea329168cc3938cR3)
> 
> well thats wrong but he atleast accepted his mistake and fixed it later on not like derpfest devs derpfest is just rebranded aex with 34521 picks from few 10-20 roms and gamespace lol

But still he is thief. Whatever he doing, can't deny that he steal before

**Comment by octaphene** [comment]
> > > Look the actual thief, removed copyright. Then get caught up and amend the commit lmao. Suck neobuggy dick [crdroidandroid/android_packages_apps_GameSpace@5491d62#diff-b8612be0ca7904aab0cafe581788e1b998893c4b681fdd0e1ea329168cc3938cR3](https://github.com/crdroidandroid/android_packages_apps_GameSpace/commit/5491d624c1c9f6ee5d33c165698eb9f7b9178979#diff-b8612be0ca7904aab0cafe581788e1b998893c4b681fdd0e1ea329168cc3938cR3)
> > 
> > 
> > well thats wrong but he atleast accepted his mistake and fixed it later on not like derpfest devs derpfest is just rebranded aex with 34521 picks from few 10-20 roms and gamespace lol
> 
> But still he is thief. Whatever he doing, can't deny that he steal before

yeah thats bad but arent derp picked commits authored by theif lol

**Comment by azrim** [comment]
> > > > Look the actual thief, removed copyright. Then get caught up and amend the commit lmao. Suck neobuggy dick [crdroidandroid/android_packages_apps_GameSpace@5491d62#diff-b8612be0ca7904aab0cafe581788e1b998893c4b681fdd0e1ea329168cc3938cR3](https://github.com/crdroidandroid/android_packages_apps_GameSpace/commit/5491d624c1c9f6ee5d33c165698eb9f7b9178979#diff-b8612be0ca7904aab0cafe581788e1b998893c4b681fdd0e1ea329168cc3938cR3)
> > > 
> > > 
> > > well thats wrong but he atleast accepted his mistake and fixed it later on not like derpfest devs derpfest is just rebranded aex with 34521 picks from few 10-20 roms and gamespace lol
> > 
> > 
> > But still he is thief. Whatever he doing, can't deny that he steal before
> 
> yeah thats bad but arent derp picked commits authored by theif lol

Cherry-picked with proper authorship, What's wrong with that?

**Comment by octaphene** [comment]
> > > > > Look the actual thief, removed copyright. Then get caught up and amend the commit lmao. Suck neobuggy dick [crdroidandroid/android_packages_apps_GameSpace@5491d62#diff-b8612be0ca7904aab0cafe581788e1b998893c4b681fdd0e1ea329168cc3938cR3](https://github.com/crdroidandroid/android_packages_apps_GameSpace/commit/5491d624c1c9f6ee5d33c165698eb9f7b9178979#diff-b8612be0ca7904aab0cafe581788e1b998893c4b681fdd0e1ea329168cc3938cR3)
> > > > 
> > > > 
> > > > well thats wrong but he atleast accepted his mistake and fixed it later on not like derpfest devs derpfest is just rebranded aex with 34521 picks from few 10-20 roms and gamespace lol
> > > 
> > > 
> > > But still he is thief. Whatever he doing, can't deny that he steal before
> > 
> > 
> > yeah thats bad but arent derp picked commits authored by theif lol
> 
> Cherry-picked with proper authorship, What's wrong with that?

nothing just telling in general if someone is theft u should'nt pick from him start boycotting neobuddy commits from now but than uh where will u get ur features from

**Comment by NurKeinNeid** [comment]
Lol, he never created any feature. He only cherry-picks. Nothing unique as always.

**Pull request closed without merging**
